### PR TITLE
updated readme with deployment steps

### PR DESCRIPTION
**Pull request by yolandeleungFT**

### CODE REVIEW

**Comment by peter-mouland** [comment]
just wondering why we have introduced a staging? do we have smoke test or integration tests that can only be run in a staging environment?

I only ask because we do peer-reviews (and testing) before merging to master at the moment. and before we had continuous deployment. So i'm wondering if we are losing continuous deployment for a specific reason?

**Comment by radiodario** [comment]
I think the common practice is to create a `DEPLOYING.md` file for deploying instructions (i.e. in the same fashion as `CONTRIBUTING.md` and `RELEASING.md`.

Anyway, i agree with pete in that adding the staging stage removes continuous deployment. When do we move staging to master? do we implement a Release Day?

**Comment by yolandeleungFT** [comment]
I can move it into a deploying.md if you prefer.

I don't think adding staging necessarily inhibits continuous deployment
because in continuous deployment your releases can still be phased/staged.
What concerns me a little more is not being able to tag an artifact, and
that features can build up on the staging branch if you have not taken a
tag of the merges in front since Heroku _builds_ and deploys.

So staging is our QA sign off area right? When the nightingale publish app
itself needs to be testable against the test API and writing to Asana,
there needs to be an app (whatever we call it prod or staging) to test
with. Are your concerns to do with the gated approach? I know there is a
push generally to not have as many QA environments, and one solution (imo)
is to deploy an app that is "prod-like" that is interchangeable with the
present prod app. This works with a bunch of stateless microservices and
then you do not have to just through staging to get to prod.

I have been told the branching strategy has been adopted because it is how
circleci recommends configuration. These are the processes that this team
has adopted. They are new to me also if you have a better ideas then we
should raise and discuss.

On 29 July 2015 at 16:53, Dario notifications@github.com wrote:

> I think the common practice is to create a DEPLOYING.md file for
> deploying instructions (i.e. in the same fashion as CONTRIBUTING.md and
> RELEASING.md.
> 
> Anyway, i agree with pete in that adding the staging stage removes
> continuous deployment. When do we move staging to master? do we implement a
> Release Day?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Financial-Times/nightingale-publish-alert/pull/7#issuecomment-125997026
> .

## 

_Yolande Leung_
Senior Developer
FT Engineering

+44 (0)20 7873 4402
Number One Southwark Bridge, London SE1 9HL

https://www.facebook.com/financialtimes https://twitter.com/FT
http://www.linkedin.com/company/financial-times
https://plus.google.com/+FinancialTimes/posts
http://www.youtube.com/user/FinancialTimesVideos

## 

---

This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by yolandeleungFT** [comment]
We move from staging to master when Mo is satisfied with the build.

**Comment by peter-mouland** [comment]
I think it was something chosen for a single project, but not adopted by the team as such.  yeah, Sounds like a good timeout session to be had after standup :)

**Pull request merged**
