### PR TITLE
Poller tests

### LINKED ISSUE #14: Add tests for poller
Add tests with mocked 3rd party API (see https://www.npmjs.com/package/nock).

### PR DESCRIPTION
**Pull request by radiodario**
mocked api tests for poller and notifier - fixes #14

### CODE REVIEW

**Comment by Lucas-Gluchowski** [comment]
Could we have all 3 types of articles, i.e. Methode, FastFT and blogs?
How about mocking notifier? It uses Asana and Slack APIs.

**Comment by radiodario** [comment]
what do we get from mocking a third party api? I don't really see the point but i can do it.

**Comment by Lucas-Gluchowski** [comment]
so that our tests are not dependant on Asana and Slack availability. Note that currently NPA uses staging Asana instance in it's test. But this is a lower priority than covering missing cases IMHO.

**Comment by radiodario** [comment]
cool, i'll fix that!

**Comment by radiodario** [comment]
Ok, all of the external third party APIs have been mocked, and all public methods have unit tests.

**Comment by radiodario** [comment]
@Lucas-Gluchowski

**Comment by radiodario** [comment]
oh yeah and this fixes #14

**Pull request merged**
